
export const  products = [
  {
    id: 1,
    name: 'Product A',
    category: 'smartphones',
    price: 49.99,
    image: '/images/electronics.jpg',
    description: 'A stylish and durable watch perfect for everyday useA stylish and durable watch perfect for everyday use.',
    brand: 'BrandA',
  },
  {
    id: 2,
    name: 'Accessories',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'Elegant watch with leather strap and water-resistant design.',
    brand: 'BrandB',
  },
  {
    id: 3,
    name: 'Laptop',
    category: 'Laptop',
    price: 89.99,
    image: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?auto=format&fit=crop&w=800&q=80',
    description: 'Fashionable accessory to complement any outfit.',
    brand: 'BrandC',
  },
  {
    id: 4,
    name: 'Product B',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'High-quality accessory made from premium materials.',
    brand: 'BrandD',
  },
  {
    id: 5,
    name: 'Product B',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'Trendy and comfortable to wear all day long.',
    brand: 'BrandE',
  },
  {
    id: 6,
    name: 'Product B',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'Perfect accessory for casual and formal occasions.',
    brand: 'BrandF',
  },
  {
    id: 7,
    name: 'Product B',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'Classic design with a modern touch.',
    brand: 'BrandG',
  },
  {
    id: 8,
    name: 'Product B',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'Lightweight and durable accessory for everyday use.',
    brand: 'BrandH',
  },
  {
    id: 9,
    name: 'Product B',
    category: 'Accessories',
    price: 89.99,
    image: '/images/fashion.jpg',
    description: 'Elegant accessory that enhances your style.',
    brand: 'BrandI',
  }
];

